template: 'facelessuser:master-labels:labels.yml:master'

# Wildcard labels

brace_expansion: true
extended_glob: true
minus_negate: false

rules:
  - labels: ['C: infrastructure']
    patterns: ['*|!@(*.md|*.py|*.sublime-@(keymap|menu|settings|commands))', '@(requirements|.github)/**']

  - labels: ['C: source']
    patterns: ['**/@(*.py|*.sublime-@(keymap|menu|settings|commands))|!tests']

  - labels: ['C: docs']
    patterns: ['**/*.md|docs/**']

  - labels: ['C: tests']
    patterns: ['tests/**']

  - labels: ['C: plugins']
    patterns: ['bh_modules/**|bh_plugin.py']

  - labels: ['C: swapping']
    patterns: ['**/*swapping*']

  - labels: ['C: wrapping']
    patterns: ['**/*wrapping*']

  - labels: ['C: core']
    patterns: ['**/*core*']

  - labels: ['C: logging']
    patterns: ['bh_logging.py']

  - labels: ['C: popups']
    patterns: ['bh_popup.py']

  - labels: ['C: regions']
    patterns: ['bh_regions.py']

  - labels: ['C: remove']
    patterns: ['bh_remove.py']

  - labels: ['C: rules']
    patterns: ['bh_rules.py']

  - labels: ['C: search']
    patterns: ['bh_search.py']

  - labels: ['C: tags']
    patterns: ['**/bh_modules/tag@(s|attrselect|nameselect).py|bh_tag.sublime-settings']

  - labels: ['C: settings']
    patterns: ['*.sublime-@(keymap|menu|settings|commands)']

  - labels: ['C: icons']
    patterns: ['**/icons/*']

# Label management

labels:
- name: 'C: plugins'
  renamed: plugins
  color: subcategory
  description: Related to plugins.

- name: 'C: swapping'
  renamed: swapping
  color: subcategory
  description: Related to the swapping library.

- name: 'C: wrapping'
  renamed: wrapping
  color: subcategory
  description: Related to the wrapping library.

- name: 'C: core'
  renamed: core
  color: subcategory
  description: Related to the core code.

- name: 'C: logging'
  renamed: logging
  color: subcategory
  description: Related to logging

- name: 'C: popups'
  renamed: popups
  color: subcategory
  description: Related to popups

- name: 'C: regions'
  renamed: regions
  color: subcategory
  description: Related to regions.

- name: 'C: remove'
  renamed: remove
  color: subcategory
  description: Related to bracket removal.

- name: 'C: rules'
  renamed: rules
  color: subcategory
  description: Related to bracket rules.

- name: 'C: search'
  renamed: search
  color: subcategory
  description: Related to search.

- name: 'C: tags'
  renamed: tags
  color: subcategory
  description: Related to tag handling.

- name: 'C: settings'
  renamed: settings
  color: subcategory
  description: Related to Sublime settings files.

- name: 'C: icons'
  renamed: icons
  color: subcategory
  description: Bracket icons.
